package org.example.calculatorapp.domains.expression_evaluator

import org.example.calculatorapp.constants.domains.ExpressionEvaluatorConstants.NOT_VALID_EXPRESSION_EXCEPTION_MESSAGE

class NotValidExpressionException : Exception(NOT_VALID_EXPRESSION_EXCEPTION_MESSAGE)